---
apiVersion: v1
kind: Namespace
metadata:
  name: seclock

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: seclock-deployment
  namespace: seclock
spec:
  replicas: 2
  selector:
    matchLabels:
      app: seclock
  template:
    metadata:
      labels:
        app: seclock
    spec:
      containers:
        - name: seclock
          image: 208805232757.dkr.ecr.ap-south-1.amazonaws.com/seclock:latest
          ports:
            - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: seclock-service
  namespace: seclock
spec:
  type: LoadBalancer
  selector:
    app: seclock
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
